apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sample-app-secret
  namespace: online-boutique
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: sample-app-secret
    creationPolicy: Owner
  data:
    - secretKey: db-password
      remoteRef:
        key: db-password-sample
