apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app-online-boutique.yaml
  - app-argocd.yaml
  - app-envoy-gateway.yaml
  - app-cert-manager.yaml
  - app-platform-cert-manager.yaml
  - app-platform-gateway.yaml
  - app-external-secrets.yaml
  - app-platform-external-secrets.yaml
  - app-argo-rollouts.yaml
  - app-platform-argo-rollouts.yaml
  - app-kube-prometheus-stack.yaml
  - app-platform-observability.yaml
