apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: online-boutique

resources:
  - ../../base
  - namespace.yaml

patches:
  - path: patches/dev-resources.yaml

images:
  - name: acrdevsrelab01.azurecr.io/frontend
    newName: acrdevsrelab01.azurecr.io/frontend
    newTag: sha-d6d7fb8
