apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: online-boutique

resources:
  - ../../base
  - namespace.yaml

patches:
  - path: patches/prod-resources.yaml

images:
  - name: acrdevsrelab01.azurecr.io/frontend
    newName: acrdevsrelab01.azurecr.io/frontend
    newTag: v1.0.0
